- name: install and run nginx
  hosts: web
  become: yes
  tasks:
    - name: Install nginx
      ansible.builtin.package:
        name: nginx
        state: present
    - name: start service nginx, if not started
      ansible.builtin.service:
        name: nginx
        state: started
