#Variables from task level
- name: variable from task level
  hosts: localhost
  vars_files:
    - variables.yaml
  tasks:
    - name: check variables
      # vars:
      #   # course: "DevOps from task"
      #   # duration: "120 task"
      ansible.builtin.debug:
        msg: "Hi, I am learning {{course}}, {{duration}}"
