- name: variable from prompt level
  hosts: localhost
  vars_prompt:
    - name: USERNAME
      prompt: Please enter the username
      private: false
    - name: Password
      prompt: please enter your password
      private: true
  tasks:
    - name: giving variables from pompt
      ansible.builtin.debug:
      msg: "hell0 {{USERNAME}} {Password}"
