#Variables from task level
- name: variable from task level
  hosts: local
  # vars:
  #   course: "DevOps"
  #   duration: "120"
  tasks:
    - name: check variables
      # vars:
      #   course: "DevOps from task"
      #   duration: "120 task"
      ansible.builtin.debug:
        msg: "Hi, I am learning {{course}}, {{Duration}}"
