- name: Variable from the play level
  hosts: localhost
  tasks:
    - name: check variables
      ansible.builtin.debug:
        msg: "Hello {{name}} {{Password}}"
# ansible-playbook -i inventory -e ansible_user=osboxes -e ansible_password=1240@Uppu -e "name=siva" -e "Password=ramesh" 09-vars-from-args.yaml command tu run

