- name: check the loops
  hosts: localhost
  tasks:
    - name: check roboshop user exsists or not
      ansible.builtin.command: id roboshop
      register: user #user is the vriable
      ignore_errors: true #this will igore the erros in the ansible
    - name: print variable value
      ansible.builtin.debug:
        msg: "User output is: {{user}}"
    - name: print variable value
      ansible.builtin.debug:
        msg: "User output is: {{user.rc}}"
    - name: creating user
      ansible.builtin.user:
        name: roboshop
      when: {{user.rc}} !=0 ##checks the condition user exsists or not
