- name: check the loops
  hosts: localhost
  become: yes
  become_password: "{{ 1240@Uppu }}"
  tasks:
    - name: check roboshop user exsists or not
      ansible.builtin.command: id roboshop
      register: user #user is the vriable
      ignore_errors: true #this will igore the erros in the ansible
    - name: print variable value
      ansible.builtin.debug:
        msg: "User output is: {{user}}"
    - name: print variable value
      ansible.builtin.debug:
        msg: "User output is: {{user.rc}}"
    - name: create user
      ansible.builtin.user:
        name: roboshop
      when: user.rc != 0 #condition ##checks the condition user exsists or not
